apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-entry-point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-entry-point
  template:
    metadata:
      labels:
        app: rest-entry-point
    spec:
      containers:
        - name: rest-entry-point
          image: yevgenykcx/rest-entry-point-example
          imagePullPolicy: Always
          ports: 
            - containerPort: 8181
          env:
          - name: server_ip
            value: ""
          - name: PROPAGATOR_EXAMPLE_URL
            value: http://propagator:8182
          - name: JPA_EXAMPLE_URL
            value: http://jpa:8183
---
apiVersion: v1
kind: Service
metadata:
  name: rest-entry-point
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 31181
  selector:
    app: rest-entry-point
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: propagator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propagator
  template:
    metadata:
      labels:
        app: propagator
    spec:
      containers:
        - name: propagator
          image: yevgenykcx/propagator-example
          imagePullPolicy: Always
          ports: 
            - containerPort: 8182
          env:
          - name: server_ip
            value: ""
          - name: rest-entry-point
            value: http://rest-entry-point:8181
          - name: JPA_EXAMPLE_URL
            value: http://jpa:8183
---
apiVersion: v1
kind: Service
metadata:
  name: propagator
spec:
  type: NodePort
  ports:
    - port: 8182
      targetPort: 8182
      nodePort: 31182
  selector:
    app: propagator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpa
  template:
    metadata:
      labels:
        app: jpa
    spec:
      containers:
        - name: jpa
          image: yevgenykcx/jpa-example
          imagePullPolicy: Always
          ports: 
            - containerPort: 8183
          env:
          - name: server_ip
            value: ""
          - name: rest-entry-point
            value: http://rest-entry-point:8181
          - name: propagator
            value: http://propagator:8182
---
apiVersion: v1
kind: Service
metadata:
  name: jpa
spec:
  type: NodePort
  ports:
    - port: 8183
      targetPort: 8183
      nodePort: 31183
  selector:
    app: jpa
