
export const DEPOSIT_DURATION = 2000
export const CHECK_BALANCE_DURATION = 2000
export const LOGIN_DURATION = 1000
export const REGISTER_DURATION = 1000
export const LOGS_UPDATE_DURATION = 300
export const CURRENCY_CONVERSION_DURATION = 1800
export const CHECK_LOAN_CREDIBILITY_DURATION = 2000
