version: "3"

services:
  mysql:
    image: mysql:5
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    expose:
    - "3306"

  node-http-entry-point:
    image: 'yevgenykcx/node-http-entry-point'
    ports:
      - '5010:5010'
    environment:
      - NODEJS_REST_PROPAGATOR_EXAMPLE_URL=http://node-http-propagator:5011
      - NODEJS_REST_SINK_EXAMPLE_URL=http://node-http-sink:5012
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    restart: on-failure
    
  node-http-propagator:
    image: 'yevgenykcx/node-http-propagator'
    ports:
      - '5011:5011'
    environment:
      - NODEJS_REST_ENTRY_POINT_EXAMPLE_URL=http://node-http-entry-point:5010
      - NODEJS_REST_SINK_EXAMPLE_URL=http://node-http-sink:5012
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    restart: on-failure
    
  node-http-sink:
    image: 'yevgenykcx/node-http-sink'
    ports:
      - '5012:5012'
    environment:
      - NODEJS_REST_ENTRY_POINT_EXAMPLE_URL=http://node-http-entry-point:5010
      - NODEJS_REST_PROPAGATOR_EXAMPLE_URL=http://node-http-propagator:5011
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
      - MYSQL_URL=mysql
    restart: on-failure